name: Yearmarked
version: 1.0.3
main:  com.blocktyper.yearmarked.YearmarkedPlugin
author: spaarkimus
website: blocktyper.com
database: false
description: Keeps track of days/months/years and triggers special events in game
softdepend: [HolographicDisplays]

commands:
  yearmarked: 
    description: changes time according to the arguments provided
  ym: 
    description: changes time according to the arguments provided
